#:schema node_modules/wrangler/config-schema.json
name = "do"
main = "src/index.ts"
compatibility_date = "2024-09-25"

[[durable_objects.bindings]]
name = "BLOCK"
class_name = "Block"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Block"]
